### ISSUE TITLE
Missing object InsertCategoryLog

### ISSUE THREAD

**Issue by vivek0j** [Infosys/Script-Control-Center#3]
Facing error: [The module ADDcategory depends on the missing object ] InsertCategoryLog
while running the scipt "CreateObjects_IAPWEM_Logs.sql"

**Comment by abdulsajid95** [comment]
The query should have executed successfully, the reason this message is shown is because in the query two stored procedures (addcategory and insertcategorylog) are being created in which one is dependent on the other. Execution should be in the order of InsertCategoryLog and then addcategory. So this is not an error.

**Comment by vivek0j** [comment]
Hi Abdul, recieving "server error in  /'iapscriptstore' Application, the network  path  not  found " error.
how I overcome this

**Comment by vivek0j** [comment]
Hi, Now I'm getting no endpoint listening error, from where I should pass our ssc_servername because the server mentioned on error is not ours.
Mentioned ssc_servername : "http://ssc_servername/iapwemservices/WEMSecurityAccessService....."

**Comment by abdulsajid95** [comment]
You need to update the web.config files. ssc_servername should be replaced by your machine name where you have setup your script control center. Also you can close the issue if the resolution is satisfactory. You can always raise a new issue for new errors that way we will have one issue related to one topic/error.

**Comment by vivek0j** [comment]
Ok, Thank You
